# Generated by Django 5.0 on 2024-02-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_release_date_movie_revenue_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='tmdb_movie_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
